apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-1
    app.kubernetes.io/part-of: vroom-app
  name: python-1
  namespace: nmukherj
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-1
    weight: 100
status: {}
